import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../public/globals.css";

import { FirebaseNextJSProvider } from "firebase-nextjs/client/auth";
import { getUserSS } from "firebase-nextjs/server/auth";
import MainLayout from "@/components/main-layout/main-layout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  const user = await getUserSS();

  return (
    <html lang="en">
      <FirebaseNextJSProvider>
        <body className={inter.className}>
          <>{user?.uid ? <MainLayout>{children}</MainLayout> : children}</>
        </body>
      </FirebaseNextJSProvider>
    </html>
  );
}